### ISSUE TITLE
Requirements issue

### ISSUE THREAD

**Issue by davezeking** [pR0Ps/strava-backup#4]
There seems to be a missing = sign on line 18 of setup.py.  The current requirement for the stravalib library is written as >0.10.2, since the library is still at v0.10.2 the requirement is not satisfied and the pip install command does not work. I think the line should be:

`install_requires=["stravaweblib>=0.0.4,<1.0.0", "stravalib>=0.10.2,<1.0.0"],`

**Comment by pR0Ps** [comment]
Thanks for pointing this out, it's now fixed!
